---
name: "opendds-monitor CI"
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: '10 0 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        opendds_branch:
          # - master
          # - latest-release
          - fix_macos_ipv6_issue
        runner:
          - windows-2022
          - windows-2019
          - ubuntu-22.04
          - ubuntu-20.04
          - macos-12
          - macos-11

    runs-on: ${{ matrix.runner }}

    steps:
      # Check out opendds-monitor
      - name: 'Checkout opendds-monitor'
        uses: actions/checkout@v3

      # Check out MPC / ACE_TAO / OpenDDS
      - name: 'Checkout MPC'
        uses: actions/checkout@v3
        with:
          repository: DOCGroup/MPC
          path: MPC
          fetch-depth: 1
      - name: 'Checkout ACE_TAO'
        uses: actions/checkout@v3
        with:
          repository: DOCGroup/ACE_TAO
          ref: ace6tao2
          path: ACE_TAO
          fetch-depth: 1
      - name: 'Checkout OpenDDS'
        uses: actions/checkout@v3
        with:
          repository: simpsont-oci/OpenDDS
          ref: ${{ matrix.opendds_branch }}
          path: OpenDDS
          fetch-depth: 1

      # Pull Down Pre-Built Dependencies
      - name: 'Install ssl, xerces, qt5, and qwt (Linux)'
        if: runner.os == 'Linux'
        run: |-
          sudo apt-get update
          sudo apt-get -y install libssl-dev libxerces-c-dev libqwt-qt5-dev
      - name: 'Install xerces, qt5, and qwt (macOS)'
        if: runner.os == 'macOS'
        run: |
          brew install xerces-c qt5 qwt
      - name: 'Install openssl, xerces, qt5, and qwt (Windows)'
        if: runner.os == 'Windows'
        uses: lukka/run-vcpkg@v7
        with:
          vcpkgGitCommitId: b86c0c35b88e2bf3557ff49dc831689c2f085090
          vcpkgArguments: --recurse openssl xerces-c qt5 qwt
          vcpkgTriplet: x64-windows

      # Debugging
      - name: 'Debugging(Windows)'
        if: runner.os == 'Windows'
        shell: cmd
        run: |-
          dir D:\a\opendds-monitor\opendds-monitor\vcpkg\installed\x64-windows

      # Set Up Some Necessary / Helpful Build Tools
      - name: 'Set Up MSVC Environment'
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
      - name: 'Set Up Problem Matcher (Windows)'
        if: runner.os == 'Windows'
        uses: ammaraskar/msvc-problem-matcher@0.1
      - name: 'Set Up Problem Matcher (Linux / macOS)'
        if: runner.os == 'Linux' || runner.os == 'macOS'
        uses: ammaraskar/gcc-problem-matcher@0.1

      # Set Environment Variables
      - name: 'Set environment variables (Linux / macOS)'
        if: runner.os == 'Linux' || runner.os == 'macOS'
        shell: bash
        run: |-
          echo "ACE_ROOT=$GITHUB_WORKSPACE/ACE_TAO/ACE" >> $GITHUB_ENV
          echo "TAO_ROOT=$GITHUB_WORKSPACE/ACE_TAO/TAO" >> $GITHUB_ENV
          echo "DDS_ROOT=$GITHUB_WORKSPACE/OpenDDS" >> $GITHUB_ENV
          echo "MPC_ROOT=$GITHUB_WORKSPACE/MPC" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$GITHUB_WORKSPACE/ACE_TAO/ACE/lib:$GITHUB_WORKSPACE/OpenDDS/lib" >> $GITHUB_ENV
          CONFIG_OPTIONS+=" --no-tests --ipv6 --security"
          if [ '${{ runner.os }}' == 'macOS' ]; then
            CONFIG_OPTIONS+=" --xerces3=/usr/local/Cellar/xerces-c/3.2.3 --openssl=/usr/local/opt/openssl@1.1"
          fi
          echo "CONFIG_OPTIONS=$CONFIG_OPTIONS" >> $GITHUB_ENV
      - name: 'Set environment variables (Windows)'
        if: runner.os == 'Windows'
        shell: bash
        run: |-
          echo "ACE_ROOT=$GITHUB_WORKSPACE\\ACE_TAO\\ACE" >> $GITHUB_ENV
          echo "TAO_ROOT=$GITHUB_WORKSPACE\\ACE_TAO\\TAO" >> $GITHUB_ENV
          echo "DDS_ROOT=$GITHUB_WORKSPACE\\OpenDDS" >> $GITHUB_ENV
          echo "MPC_ROOT=$GITHUB_WORKSPACE\\MPC" >> $GITHUB_ENV
          CONFIG_OPTIONS+=" --no-tests --ipv6 --security --xerces3=\"$VCPKG_ROOT\\installed\\x64-windows\" --openssl=\"$VCPKG_ROOT\\installed\\x64-windows\""
          echo "CONFIG_OPTIONS=$CONFIG_OPTIONS" >> $GITHUB_ENV

      # Configure OpenDDS
      - name: 'Configure & Build OpenDDS (Linux / macOS)'
        if: runner.os == 'Linux' || runner.os == 'macOS'
        shell: bash
        run: |-
          cd OpenDDS
          ./configure ${{ env.CONFIG_OPTIONS }}
      - name: 'Configure OpenDDS (Windows)'
        if: runner.os == 'Windows'
        shell: cmd
        run: |-
          cd OpenDDS
          configure ${{ env.CONFIG_OPTIONS }}

      # Build OpenDDS
      - name: 'Build OpenDDS (Linux / macOS)'
        if: runner.os == 'Linux' || runner.os == 'macOS'
        shell: bash
        run: |-
          cd OpenDDS
          . setenv.sh
          make -j3
      - name: 'Build OpenDDS (Windows)'
        if: runner.os == 'Windows'
        shell: cmd
        run: |-
          cd OpenDDS
          call setenv.cmd
          msbuild -p:Configuration=Debug,Platform=x64 -m DDS_TAOv2.sln

      # Build opendds-monitor
      - name: 'Build opendds-monitor (Linux / macOS)'
        if: runner.os == 'Linux' || runner.os == 'macOS'
        shell: bash
        run: |-
          cd OpenDDS
          . setenv.sh
          cd ..
          mkdir build
          cd build
          cmake ..
          make
      - name: 'Build opendds-monitor (Windows)'
        if: runner.os == 'Windows'
        shell: cmd
        run: |-
          cd OpenDDS
          call setenv.cmd
          cd ..
          mkdir build
          cd build
          cmake -DCMAKE_PREFIX_PATH=%VCPKG_ROOT%\installed\x64-windows ..
          msbuild -p:Configuration=Debug,Platform=x64 -m opendds-monitor.sln

